"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so a real key never has to live in source
# control. The fallback below is a throwaway value, valid for local
# development only — any real deployment should set DJANGO_SECRET_KEY as
# an actual environment variable with its own generated key. See
# .env.example.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-8x#h3f!q9k2m$w7z@r5t1v6n0y4b_dpia+demo",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Render sets RENDER_EXTERNAL_HOSTNAME to the service's public hostname at
# runtime — it isn't known in advance, so it can't just go in
# DJANGO_ALLOWED_HOSTS ahead of time. Trust it automatically when present;
# a custom domain still needs to be added via DJANGO_ALLOWED_HOSTS.
_render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_hostname:
    ALLOWED_HOSTS.append(_render_hostname)
    CSRF_TRUSTED_ORIGINS = [f"https://{_render_hostname}"]
else:
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]

# Render (like most PaaS hosts) terminates TLS at the edge and forwards
# requests to the app over plain HTTP with this header set — without it
# Django can't tell the request was actually HTTPS, which breaks CSRF and
# secure-cookie checks.
if os.environ.get("RENDER"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Belt-and-suspenders production hardening, checked against
# `manage.py check --deploy`. Render already forces HTTPS at the edge for
# every service, so none of this is filling a gap there today — it's here
# so the app stays correctly configured if it's ever hosted somewhere that
# doesn't do that for you.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dpia",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files directly from the app process — this app's
    # static payload is small enough that a separate CDN/static host
    # would be overkill, and WhiteNoise keeps the Render deploy to a
    # single web service with no extra infrastructure.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite locally (zero setup, matches the README's local-dev instructions).
# The DPIA wizard's multi-step state lives in the database-backed session
# store (Django's default), so it survives across requests/workers the
# same way any other model data does — set DATABASE_URL to switch to
# Postgres in production with no code changes.
_database_url = os.environ.get("DATABASE_URL")

if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
# Serve straight from STATICFILES_DIRS instead of requiring collectstatic
# to have run first — this app's static payload is one CSS file, so the
# (real, but here irrelevant) performance cost of skipping the
# manifest/hashing is a non-issue, and it keeps `manage.py runserver` and
# `manage.py test` working with zero build step, matching local dev.
WHITENOISE_USE_FINDERS = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site-wide display name, used in the base template <title> and the DPIA
# PDF export filename. Kept as a setting rather than hard-coded so it only
# needs to change in one place.
SITE_TITLE = "DPIA-Privacy-Impact-Assessment"
