"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so a real key never has to live in source
# control. The fallback below is a throwaway value, valid for local
# development only — any real deployment should set DJANGO_SECRET_KEY as
# an actual environment variable with its own generated key. See
# .env.example.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-8x#h3f!q9k2m$w7z@r5t1v6n0y4b_dpia+demo",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Vercel sets these at runtime — VERCEL_URL to the *current deployment's*
# unique hostname (a new one every deploy), VERCEL_PROJECT_PRODUCTION_URL
# to the stable production alias (e.g. dpia-privacy-impact-assessment.vercel.app).
# Neither is known in advance, so they can't just go in
# DJANGO_ALLOWED_HOSTS — trust both automatically when present. A custom
# domain still needs to be added via DJANGO_ALLOWED_HOSTS.
_vercel_hosts = [
    h
    for h in (
        os.environ.get("VERCEL_URL"),
        os.environ.get("VERCEL_PROJECT_PRODUCTION_URL"),
    )
    if h
]
if _vercel_hosts:
    ALLOWED_HOSTS.extend(_vercel_hosts)
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in _vercel_hosts]
else:
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]

# Vercel (like most serverless/PaaS hosts) terminates TLS at the edge and
# forwards requests to the app over plain HTTP with this header set —
# without it Django can't tell the request was actually HTTPS, which
# breaks CSRF and secure-cookie checks.
if os.environ.get("VERCEL"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Belt-and-suspenders production hardening. Vercel already forces HTTPS
# and sends HSTS/X-Content-Type-Options/X-Frame-Options at the edge for
# every deployment, so none of this is filling a gap there today — it's
# here so the app is still correctly configured if it's ever hosted
# somewhere that doesn't do that for you. `manage.py check --deploy` was
# used to find this list.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "dpia",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files directly from the app process. Vercel's
    # serverless functions have no separate static file server and no
    # persistent disk to run `collectstatic` into ahead of time, so
    # WhiteNoise (with WHITENOISE_USE_FINDERS below) serves them straight
    # from the source directories on every request — simplest thing that
    # works for this app's tiny CSS footprint.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# SQLite locally (zero setup, matches the README's local-dev instructions).
# In production — Vercel's serverless functions have no persistent disk,
# so a SQLite file wouldn't survive between requests — set DATABASE_URL
# (Vercel's Postgres/Neon integration injects POSTGRES_URL automatically;
# either name is read here) to switch to Postgres with no code changes.
# The DPIA wizard's multi-step state lives in the database-backed session
# store (Django's default), so it survives across serverless invocations
# the same way any other model data does — no serverless-specific
# handling needed beyond having a real database configured.
_database_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")

if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
# Serve straight from STATICFILES_DIRS instead of requiring collectstatic
# to have run first — this app's static payload is one CSS file, so the
# (real, but here irrelevant) performance cost of skipping the
# manifest/hashing is a non-issue, and it keeps `manage.py runserver` and
# `manage.py test` working with zero build step, matching local dev.
WHITENOISE_USE_FINDERS = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Site-wide display name, used in the base template <title> and the DPIA
# PDF export filename. Kept as a setting rather than hard-coded so it only
# needs to change in one place.
SITE_TITLE = "DPIA-Privacy-Impact-Assessment"
