# Generated by Django 6.1.1 on 2026-09-03 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Name of the new processing activity or project being assessed.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short summary of what's being proposed and why this assessment exists."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="What this risk factor means and why it raises DPIA risk."
                    ),
                ),
                (
                    "severity_weight",
                    models.PositiveSmallIntegerField(
                        help_text="Internal 1-3 severity scale used by the risk-scoring model (see dpia/scoring.py)."
                    ),
                ),
            ],
            options={
                "ordering": ("-severity_weight", "name"),
            },
        ),
        migrations.CreateModel(
            name="NecessityProportionality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "necessity_justification",
                    models.TextField(
                        help_text="Why this purpose can't reasonably be achieved without this processing."
                    ),
                ),
                (
                    "proportionality_justification",
                    models.TextField(
                        help_text="Why the amount/type of data processed is proportionate to the purpose."
                    ),
                ),
                (
                    "alternatives_considered",
                    models.TextField(
                        blank=True,
                        help_text="Less intrusive alternatives that were considered and why they were rejected.",
                    ),
                ),
                (
                    "data_minimization_measures",
                    models.TextField(
                        blank=True,
                        help_text="Steps taken to limit collection/processing to what's actually needed.",
                    ),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="necessity_proportionality",
                        to="dpia.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nature",
                    models.TextField(
                        help_text="What data is collected and how it will be processed."
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        help_text="How much data, how many data subjects, how often."
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        help_text="The relationship with data subjects and what they'd reasonably expect."
                    ),
                ),
                (
                    "purpose",
                    models.TextField(help_text="Why this processing is being introduced."),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_description",
                        to="dpia.assessment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MitigationMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What this mitigation is and how it reduces the associated risk."
                    ),
                ),
                (
                    "reduction_weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many points this mitigation offsets on its risk factor's severity (1-3).",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigation_measures",
                        to="dpia.assessment",
                    ),
                ),
                (
                    "risk_factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitigation_measures",
                        to="dpia.riskfactor",
                    ),
                ),
            ],
            options={
                "ordering": ("assessment", "risk_factor"),
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="risk_factors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Risk factors judged applicable to this processing activity.",
                related_name="assessments",
                to="dpia.riskfactor",
            ),
        ),
    ]
